package com.expense.hibernate.domains;

// Generated Jul 14, 2013 4:30:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Budget generated by hbm2java
 */
@Entity
@Table(name = "budget")
public class Budget implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1526825115161323197L;
	private Long id;
	private Users usersByCreatedBy;
	private Users usersByModifiedBy;
	private Double value;
	private Integer month;
	private Integer year;

	public Budget() {
	}

	public Budget(Users usersByCreatedBy, Users usersByModifiedBy,
			Double value, Integer month, Integer year) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByModifiedBy = usersByModifiedBy;
		this.value = value;
		this.month = month;
		this.year = year;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "created_by")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "modified_by")
	public Users getUsersByModifiedBy() {
		return this.usersByModifiedBy;
	}

	public void setUsersByModifiedBy(Users usersByModifiedBy) {
		this.usersByModifiedBy = usersByModifiedBy;
	}

	@Column(name = "value", precision = 22, scale = 0)
	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	@Column(name = "month")
	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

}
