package com.expense.hibernate.domains;

// Generated Jul 14, 2013 4:30:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
public class Category implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8794871232910730196L;
	private Long id;
	private Users usersByCreatedBy;
	private Users usersByModifiedBy;
	private String categoryName;
	private Date createdDate;
	private Date modifiedDate;
	private Integer categoryType;
	private Set<Notification> notifications = new HashSet<Notification>(0);
	private Set<Expense> expenses = new HashSet<Expense>(0);

	public Category() {
	}		
	
	public Category(Long id) {
		this.id = id;
	}

	public Category(Users usersByCreatedBy, Users usersByModifiedBy,
			String categoryName, Date createdDate, Date modifiedDate,
			Integer categoryType, Set<Notification> notifications,
			Set<Expense> expenses) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByModifiedBy = usersByModifiedBy;
		this.categoryName = categoryName;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.categoryType = categoryType;
		this.notifications = notifications;
		this.expenses = expenses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "created_by")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "modified_by")
	public Users getUsersByModifiedBy() {
		return this.usersByModifiedBy;
	}

	public void setUsersByModifiedBy(Users usersByModifiedBy) {
		this.usersByModifiedBy = usersByModifiedBy;
	}

	@Column(name = "category_name", length = 145)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "category_type")
	public Integer getCategoryType() {
		return this.categoryType;
	}

	public void setCategoryType(Integer categoryType) {
		this.categoryType = categoryType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Expense> getExpenses() {
		return this.expenses;
	}

	public void setExpenses(Set<Expense> expenses) {
		this.expenses = expenses;
	}

}
