package com.expense.hibernate.domains;

// Generated Jul 14, 2013 4:30:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
/**
 * @author Jitender
 * 
 */
@Entity
@Table(name = "password_wallet")
public class PasswordWallet implements java.io.Serializable {

	private static final long serialVersionUID = -5145015026474815306L;

	private Long id;
	private Users usersByCreatedBy;
	private Users usersByModifiedBy;
	private Category category;
	private String userid;
	private String password;
	private Integer expiryDays;
	private Date createdDate;
	private Date modifiedDate;

	public PasswordWallet() {
	}

	/**
	 * @param id
	 */
	public PasswordWallet(Long id) {
		this.id = id;
	}

	/**
	 * @param id
	 * @param usersByCreatedBy
	 * @param usersByModifiedBy
	 * @param category
	 * @param userid
	 * @param password
	 * @param expiryDays
	 * @param createdDate
	 * @param modifiedDate
	 */
	public PasswordWallet(Long id, Users usersByCreatedBy,
			Users usersByModifiedBy, Category category, String userid,
			String password, Integer expiryDays, Date createdDate,
			Date modifiedDate) {
		this.id = id;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByModifiedBy = usersByModifiedBy;
		this.category = category;
		this.userid = userid;
		this.password = password;
		this.expiryDays = expiryDays;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
	}

	/**
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the usersByCreatedBy
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public Users getUsersByCreatedBy() {
		return usersByCreatedBy;
	}

	/**
	 * @param usersByCreatedBy
	 *            the usersByCreatedBy to set
	 */
	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	/**
	 * @return the usersByModifiedBy
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modified_by")
	public Users getUsersByModifiedBy() {
		return usersByModifiedBy;
	}

	/**
	 * @param usersByModifiedBy
	 *            the usersByModifiedBy to set
	 */
	public void setUsersByModifiedBy(Users usersByModifiedBy) {
		this.usersByModifiedBy = usersByModifiedBy;
	}

	/**
	 * @return the category
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return category;
	}

	/**
	 * @param category
	 *            the category to set
	 */
	public void setCategory(Category category) {
		this.category = category;
	}

	/**
	 * @return the userid
	 */
	@Column(name = "userid", length = 145)
	public String getUserid() {
		return userid;
	}

	/**
	 * @param userid
	 *            the userid to set
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * @return the password
	 */
	@Column(name = "password", length = 200)
	public String getPassword() {
		return password;
	}

	/**
	 * @param password
	 *            the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the expiryDays
	 */
	@Column(name = "expiry_days")
	public Integer getExpiryDays() {
		return expiryDays;
	}

	/**
	 * @param expiryDays
	 *            the expiryDays to set
	 */
	public void setExpiryDays(Integer expiryDays) {
		this.expiryDays = expiryDays;
	}

	/**
	 * @return the createdDate
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate
	 *            the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the modifiedDate
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return modifiedDate;
	}

	/**
	 * @param modifiedDate
	 *            the modifiedDate to set
	 */
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
