package com.expense.hibernate.domains;

// Generated Jul 14, 2013 4:30:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentMode generated by hbm2java
 */
@Entity
@Table(name = "payment_mode")
public class PaymentMode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3831759417483055825L;
	private Long id;
	private Users usersByCreatedBy;
	private Users usersByModifiedBy;
	private String paymentMode;
	private Integer paymentModeType;
	private Date createdDate;
	private Date modifiedDate;
	private Set<Expense> expenses = new HashSet<Expense>(0);

	public PaymentMode() {
	}
	
	public PaymentMode(Long id) {
		this.id = id;
	}

	public PaymentMode(Long id,Users usersByCreatedBy, Users usersByModifiedBy,
			String paymentMode, Integer paymentModeType, Date createdDate,
			Date modifiedDate, Set<Expense> expenses) {
		this.id = id;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByModifiedBy = usersByModifiedBy;
		this.paymentMode = paymentMode;
		this.paymentModeType = paymentModeType;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.expenses = expenses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "created_by")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "modified_by")
	public Users getUsersByModifiedBy() {
		return this.usersByModifiedBy;
	}

	public void setUsersByModifiedBy(Users usersByModifiedBy) {
		this.usersByModifiedBy = usersByModifiedBy;
	}

	@Column(name = "payment_mode", length = 45)
	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "payment_mode_type")
	public Integer getPaymentModeType() {
		return this.paymentModeType;
	}

	public void setPaymentModeType(Integer paymentModeType) {
		this.paymentModeType = paymentModeType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "paymentMode")
	public Set<Expense> getExpenses() {
		return this.expenses;
	}

	public void setExpenses(Set<Expense> expenses) {
		this.expenses = expenses;
	}

}
